---
title: "Kutukan Sri dan Gala"
author: "Huzaiv"
date: "25 Mei 2011"
output: 
  pdf_document:
    latex_engine: xelatex
mainfont: Linux Libertine Display O
monofont: SauceCodePro Nerd Font
---

# Prolog

Suatu ketika disuatu desa ada seorang Pemuda pendiam bernama Gala yang misterius, namun dibalik sifatnya yang dingin tersebut, dia menyimpan sebuah kekuatan untuk bertransformasi menjadi serigala..

Hari demi hari para penduduk desa pun menyadari kekuatan yang dapat membunuh mereka tersebut, hingga pada malam hari ketika fase bulan baru ketika dia tidak dapat berubah menjadi serigala jadi-jadian, para suruhan yang diperintahkan oleh Kepala desa pun membunuh Pemuda malang ini ditempat kediamannya secara diam-diam, namun keji..

Namun tak disangka, ternyata pemuda ini mempunyai seorang kekasih seorang wanita cantik bernama Sri, ketika wanita ini mengetahui kematian kekasih yang sangat dicintainya itu, dia pun murka, menangis sejadi-jadinya, dan mengutuk semua penduduk desa yang ada.

Tak disangka ternyata wanita ini juga mempunyai kekuatan magis yang bisa mengubah kata-katanya menjadi kenyataan, tanpa menyadari kekuatannya tersebut dia terus berteriak "Semoga yang membunuh kekasihku akan menjadi manusia serigala yang bengis pada malam hari! aku bersumpah!!", karena tidak tahan lagi dengan luka batinnya, diapun memilih untuk bunuh diri ditempat para pembunuh bengis ini mengubur mayat kekasihnya.

Sehari setelah wanita tersebut mengucapkan sumpah serapah dan kutukannya, keanehan pun terjadi, setiap pagi ditemukan para penduduk desa tewas dalam keadaan tubuh tercabik-cabik dan tidak utuh lagi organ tubuhnya, juga beberapa gigitan bekas Serigala... semakin hari kejadian tersebut terus berlanjut, dan klimaksnya terjadi ketika jembatan gantung yang menghubungkan mereka dengan dunia luar putus karena dirusak oleh para manusia Serigala ini dan mereka menemukan Mayat Kepala Desa yan sudah tidak berkepala lagi dikantor Kadesnya.. penduduk desa yang tersisa pun akhirnya menyadari bahwa mereka tidak seharusnya menyuruh sekelompok orang untuk membunuh pemuda tersebut, namun apa daya, mereka kini diujung tanduk..

dan akhirnya satu-satunya cara untuk selamat dari teror Serigala itu adalah tentu saja dengan membunuh mereka, para serigala kutukan dari pasangan Sri dan Gala, para penduduk harus mencari pembunuh Gala, namun tentu saja sebelum penduduk desa yang tersisa tewas!! karena mereka diantara pada penduduk tersebut!

# Peran Utama

+ Pembunuh terkutuk (Werewolves) - Makhluk jadi-jadian yang haus darah pada malam hari, memilih untuk membunuh 1 orang pada malam hari, bersama penduduk lainnya memilih satu orang untuk di eksekusi pada siang hari
+ Orang Kampung (Villager) - Tidak memiliki peran khusus, bersama penduduk lainnya memilih satu orang untuk di eksekusi pada siang hari
Pekerja tambang (Masons) - Tidak memiliki peran khusus kecuali mengetahui pekerja tambang (mason) lainnya, bersama penduduk lainnya memilih satu orang untuk di eksekusi pada siang hari
+ Dukun - (Seer) - Memiliki kemampuan untuk mengetahui peran dari 1 orang pada malam hari, bersama penduduk lainnya memilih satu orang untuk di eksekusi pada siang hari
+ Pertapa - (Guardian Angel) - Memiliki kemampuan untuk melindungi 1 orang penduduk pada malam hari dari ancaman para makhluk jadi-jadian, bersama penduduk lainnya memilih satu orang untuk di eksekusi pada siang hari
+ Jawara - (Vigilante) - Mempunyai kemampuan untuk membunuh 1 orang penduduk (hanya 1x selama game) pada malam hari, bersama penduduk lainnya memilih satu orang untuk di eksekusi pada siang hari

# Peran Sekunder

+ Sohib (Best Friend) - Karena persahabatan dari kecil 2 orang ini mengetahui peran utama satu sama lain. Apabila salah satu dari sohib mati maka sohib lainnya akan tetap hidup tetapi akan diketahui jati diri dan peran utamanya
+ Si Kembar (Twins) - Satu jiwa, itulah inti dari peran ini. Jika salah satu dari mereka mati maka kembarannya pun akan ikut mati. Kembaran tidak mengetahui peran utama kembaran lainnya.
+ Pemabuk (drunkass) - Karena hobinya yang tukang mabuk pada malam hari, pemain ini hanya bisa di bunuh oleh voting di siang hari. Peran ini hanya diberikan pada 1 pemain tim Villager
+ Tukang Gosip (gosip maker) - Bila ia mati pada malam hari maka ia akan membuka jati diri/peran utama 1 orang werewolf dan 1 orang dari tim villager (random).

# Daftar Pemain

1. `Irfan14` [Killed]
1. `FourBrothers` [Killed]
1. `ryuzakichibi` [Killed]
1. `xjocker` [Survived as Werewolf]
1. `xlimitedx` [Killed]
1. `nakasani` [Killed]
1. `YosoRoso.ver2` [Killed]
1. `pasirjengkol` [Killed]
1. `http.` [Killed]
1. `akira yosuke` [Survived as Werewolf]
1. `pushplay` [Killed]
1. `CeKilatoZ` [Killed]
1. `lukystar` [Killed]
1. `cobaltblue` [Killed]
1. `00H3nnyCute00` [Killed]
1. `jagoan_baru` [Killed]


# Kronologi

**Siang 1**

1. `lukystar` (4) (**mati karena tost koin tidak berpihak padanya**) oleh ; `YosoRoso.ver2`, `xlimitedx`, `xjocker`, `pushplay`
2. `xlimitedx` (4) oleh ; `irfan14`, `akira_yosuke`, `http.`, `ryuzaki_chibi` (sebelumnya memvote `cobaltblue`)
3. `http.` (3) oleh ; `00h3nnycute00`, `pasirjengkol`, `jagoan_baru`
4. `pushplay` (2) oleh ; `cobaltblue`, `FourBrothers`
5. `xjocker` (1) oleh ; `CeKilatoZ`
6. `jagoan_baru` (1) oleh ; `lukystar`
7. `FourBrothers` (1) oleh ; `nakasani`

`lukystar` sang Pekerja Tambang (Mason) telah Tewas!

**Malam 1**

`Jagoan_Baru` sang Pertapa (Guardian Angel) telah Tewas!

**Siang 2**

1. `pushplay` (5) (**mati karena toss coin tidak berpihak padanya**); `irfan14`, `cobaltblue`, `CeKilatoZ`, `xjocker`, `http.`
1. `xlimitedx` (5) ; `00h3nnycute00`, `ryuzakichibi`, `pasirjengkol`, `akira_yosuke`, `pushplay` (sebelumnya mengvote `YosoRoso.ver2`)
1. `FourBrothers` (2) ; `YosoRoso.ver2`, `nakasani`
1. `akira_yosuke` (1) ; `xlimitedx`
1. `CeKilatoZ` (1) ; `FourBrothers`

`pushplay` sang Villager sekaligus Gossip Makertelah Tewas!

**Malam 2**

`00h3nnycute00` sang Villagers telah Tewas! dan ternyata `ryuzaki.chibi` adalah Best Friend `00h3nnycute00` yang berperan sebagai Mason!

**Siang 3**

1. `xlimitedx` (3) oleh `irfan14`, `akira_yosuke`, `YosoRoso.ver2`,
1. `FourBrothers` (3) (**vote yang mati jatuh kepadanya**) oleh `nakasani`, `cobaltblue`, `pasirjengkol` (sebelumnya mengvote `xlimitedx`)
1. `CeKilatoZ` (3) oleh `FourBrothers`, `http.` (sebelumnya mengvote `xlimitedx`)
1. `cobaltblue` (1) oleh `xjocker`
1. `akira_yosuke` (1) oleh `xlimitedx`
1. `xjocker` (1) oleh `CeKilatoZ`

`FourBrothers` sang Pekerja Tambang (Mason) telah Tewas!

**Malam 3**

+ `xlimitedx` sang Jawara telah membunuh `pasirjengkol` sang Werewolf!
+ Werewolf telah membunuh `ryuzaki.chibi` sang Pekerja Tambang (Mason)!

**Siang 4**

1. CeKilatoZ (3) oleh xjocker, akira.yosuke, YosoRoso.ver2
1. xjocker (2) oleh CeKilatoZ, xlimitedx
1. cobaltblue (1) oleh http.
1. nakasani (1) oleh irfan14 (sebelumnya meng-vote akira.yosuke)
1. irfan14 (1) oleh nakasani

`CekilatoZ` sang Dukun (Seer) telah tewas!

**Malam 4**

`xlimitedx` sang Villagers telah tewas!

**Siang 5**

1. `xjocker` (3) ; `YosoRoso.ver2`, `http.`, `nakasani`
1. `nakasani` (4) ; `xjocker`, `irfan14`, `cobaltblue` (sebelumnya mengvote `xjocker`), `akira.yosuke`

+ `Nakasani` sang Villager telah Tewas!
+ `Cobaltblue` sang Werewolf telah Tewas!

PS : Nakasani dan Cobaltblue adalah Twins!

**Werewolf Alliances Win!**




