---
title: "The Werewolf Game - Teror Wabah Virus H19N!"
author: "<++>"
date: "<++>"
---

# PROLOG

wabah virus H19N yang sesungguhnya digunakan sebagai tonic percobaan dari air liur Siberian Husky untuk tentara dan satuan khusus keamanan, telah menyebar ke Ibukota Indonesia, yaitu Jakarta, diakibatkan kecerobohan dari petugas karantina sebuah universitas X yang secara tidak sengaja menjatuhkan dan memecahkan tabung yang berisi virus H19N dalam perjalanan, sehingga mengakibatkan virus tersebut terpapar oleh masyarakat umum dan menjadikan mereka, Serigala Jejadian!!

Kota Jakarta pun berada dalam keadaan yang chaos, kerusuhan terjadi dimana-mana, pembunuhan yang diakibatkan oleh Serigala Jejadian ini mencapai taraf yang memprihatinkan, bahkan para Menteri dan Anggota Dewan dibunuh secara sadis oleh mereka, situasi semakin kacau sampai pasukan khusus dari PBB mencoba mengamankan Jakarta diakibatkan satuan keamanan lokal sudah tidak mampu menangani para warga kota yang telah terjangkiti virus H19N ini.

penanganan pasukan khusus ini dinilai buruk sehingga mereka kembali ditarik oleh Dewan Keamanan PBB dikarenakan mereka memang tidak terlatih untuk menghadapi werewolf ini, hampir seluruh populasi Jakarta tewas akibat kekacauan ini, populasi yang tersisa pun berkumpul di Istana Merdeka.

presiden YeBeEs pun mengambil keputusan yang krusial dan terkesan egois, dia memutuskan untuk membuat kubah super besar di bekas Istana Merdeka yang masih dihuni beberapa orang yang berkumpul dari seluruh bagian Jakarta yang kini menjadi kota mati, dengan alasan Karantina, dia pun pergi dengan helikopter meninggalkan penduduk yang tersisa dikubah tersebut dan setelah itu dengan darurat menyampaikan siaran Pers tentang pemindahan Ibukota ke kota lain.

penduduk yang tersisa dalam kubah ini hanya bisa pasrah mengetahui presiden mereka Sendiri meninggalkan mereka dalam ketidakpastian, ditambah terror Werewolf yang bisa saja ada diantara mereka, satu-satunya yang bisa mereka perbuat adalah menerka siapa saja werewolf yang ada diantara mereka, tentu saja sebelum mereka dihabisi oleh werewolf tersebut!

# Peran Utama

## Villager Alliance

1. Penduduk Kota (Villagers): Player Biasa, memutuskan siapa yang harus dibunuh pada siang hari.

2. Pekerja Bangunan (Mason): Player Biasa yang saling mengetahui dengan Pekerja Bangunan (Mason) satu sama lain, memutuskan siapa yang harus dibunuh pada siang hari via vote.

3. Sniper (Vigilante): Tentara yang ditinggalkan oleh batalyon pasukannya karena suatu kecelakaan dalam operasi militer pembasmian Werewolf, berusaha untuk hidup namun hanya dibekali satu ammo dan sniper. Memutuskan siapa yang harus dibunuh pada siang hari via vote dan membunuh satu orang pada malam hari (hanya satu kali dan tidak berlaku untuk malam pertama)

4. Detektif (Seer): Seorang Penduduk dengan kemampuan menganalisa, Memutuskan siapa yang harus dibunuh pada siang hari via vote dan mengintip peran satu orang pada malam hari (tidak berlaku untuk malam pertama)

## Werewolf Alliance

1. Serigala Jejadian (Werewolf): penduduk kota yang terjangkiti virus H19N dan menjadi Serigala Jejadian, mencoba bertahan hidup. Memutuskan Siapa yang harus dibunuh pada siang hari via vote, dan memberikan vote siapa yang harus dibunuh pada malam hari via PM.

2. Pemimpin Serigala (Alpha Wolf): Pemimpin dari Serigala Jejadian. Memutuskan Siapa yang harus dibunuh pada siang hari via vote, dan ketika mati , dia dapat meng-convert satu orang dari Faksi Villager menjadi Werewolf. (hanya sekali, PM satu orang yang ingin di-convert apabila ketika mati nanti).

3. Pengkhianat (Traitor): Penduduk Kota yang berkhianat dan membelot kepada Serigala Jejadian karena alasan yang patut dipertanyakan, Memutuskan Siapa yang harus dibunuh pada siang hari via vote (karena pengkhianat, pilihlah orang paling berbahaya pada Faksi Villagers)

## Neutral Alliance

1. Psikopat (Serial Killer): penduduk kota yang gila yang hanya ingin membunuh. Memutuskan Siapa yang harus dibunuh pada siang hari via vote, dan kemampuan membunuh orang pada malam hari (Kemampuan tidak aktif pada malam pertama, beri satu target yang ingin dibunuh via PM kepada GM).


# Secondary Roles

1. Mayor (Major): Role ini diperoleh melalui vote pada siang hari oleh Faksi Villagers dan Faksi Werewolf, apabila Mayor memberikan suara, maka akan dihitung 2, bukan satu seperti biasanya.

2. Saudara Kembar (Twins): Dua Kembar yang menang apabila tetap bertahan hingga akhir permainan, apabila salah satu dari mereka mati, kembaran yang lain juga akan ikut mati. Tidak mengetahui peran satu sama lain

3. Dokter (Doctor): Peran yang diberikan secara random oleh GM pada malam hari (kecuali hari pertama) peran berpindah pindah kesetiap peserta, dapat melindungi satu orang yang ingin dilindungi ataupun diri sendiri.

4. Sohib (Best Friend): Berteman sejak kecil, mengetahui peran masing-masing. bila salah satu dari mereka mati, yang hidup akan membuka perannya.

# Daftar Pemain

1. `MissKero`
1. `Xerotess`
1. `Kaistern`
1. `Jagoan_Baru`
1. `xjocker`
1. `fix_it`
1. `nakasani`
1. `CeKilatoZ`
1. `adit_99`
1. `rendra_3`
1. `pushplay`
1. `00h3nnycute00`
1. `FourBrothers`
1. `http.`
1. `lukystar`
1. `silentvoician`
1. `irfan14`
1. `parallel`
1. `OxySterols`
1. `xlimitedx`


# Kronologi


# Final Result

`MissKero` [Killed]
`Xerotess` [Killed]
`Kaistern` [Survived]
`Jagoan_Baru` [Killed]
`xjocker` [Killed]
`fix_it` [Killed]
`nakasani` [Killed]
`CeKilatoZ` [Survived]
`adit_99` [Killed]
`rendra_3` [Killed]
`pushplay` [Killed]
`00h3nnycute00` [Killed]
`FourBrothers` [Killed]
`http.` [Killed]
`lukystar` [Survived]
`silentvoician` [Killed]
`irfan14` [Killed]

**Goodies Alliances Win!**
**Neutral Alliances Win!**
**Baddies Alliances Lose!**
