---
title: "[Board Games - TWG III] Werewolves VS Vampires :::Twilight:::"
author: "lukystar(GM) dan Pasir Jengkol(CO-GM)"
date: "<++>"
---

# Prolog

[Board Games - TWG III] Werewolves VS Vampires :::Twilight:::

Pertempuran antara werewolves dan vampires telah terjadi berabad-abad lamanya. Peperangan yan terjadi diantara keduanya seringkali membawa petaka bagi para penduduk di sekitarnya. Peperangan ini terus terjadi hingga merembet ke sebuah desa terpencil tetapi mempunyai makna penting bagi kedua faksi yang bertikai ini. Namun penduduk Desa ini dikenal sangat militan dan agresif. Setiap serangan yang dilakukan frontal baik oleh vampires maupun werewolves.

Menyadari kegagalan yang ada, akhirnya para petinggi dari kedua ras mempunyai kesimpulan yang sama untuk menguasai desa ini, MENYUSUP!!!
Para Vapires mengutus ras tertua sekaligus ketua dari Faksi mereka, COUNT DRACULA. Sedangkan werewolves mengutus serigala terkuat mereka ALPHA WOLF untuk menginfeksi para penduduk. Secara terpisah keduanya masuk ke dalam Desa dan berbaur bersama penduduk lainnya.

Namun berita ini akhirnya bocor ke tangan penduduk, Kepala Desa memutuskan untuk menutup semua akses keluar untuk mengatasi semua ini. Seluruh penduduk desa diwajibkan hadir setiap hari untuk memutuskan siapa yang akan dieksekusi setiap harinya untuk menemukan para penyusup di desa mereka.

Game terdiri dari:
3 Faksi: Werewolves, Vampires dan Villagers
2 Alignment: Good dan Evil
1 Tujuan: Membunuh semua anggota 2 faksi lainnya untuk MENANG


Jumlah Pemain yang diperlukan 30 pemain
Daftar Pemain hingga Jum'at 17 Juni 2011
1. `OxySterols`
1. `perpendicular`
1. `Xerotess`
1. `pushplay`
1. `WiryoSableng`
1. `xlimitedx`
1. `CeKilatoZ`
1. `00HennyCute00`
1. `MissKero`
1. `YosoRoso.ver2`
1. `http.`
1. `xjocker`
1. `Huzaiv`
1. `FourBrothers`
1. `jagoan baru`
1. `6May1997`
1. `irfan14`
1. `Empa1`
1. `unknown.l4w`
1. `Waika`
1. `dgr`
1. `descart`
1. `Grifiest`
1. `ReNveLaTioNa`
1. `indosphere`
1. `devil7th`
1. `cobaltblue`
1. `Killua68`
1. `R.1.C`
1. `axeon`

Bagi pemain yang ingin mendaftar atau mengundurkan diri silakan pos di trit ini...
Batas Akhir Pendaftaran adalah Ketika fase Malam ke-1 berakhir
20 Juni 2011 Pukul 21:00 WIB
PENDAFTARAN BERAKHIR!

Game Host by `Lukystar` dan `Pasir Jengkol` sebagai Co-Host

# Peran dan Item

## Peran Utama

**Dracula (Evil/ Vampires)**
Abilities:
- Merubah 1 orang menjadi vampir tiap malam, target tidak akan mengetahui siapa yang meng-convert mereka (Kecuali Minion).
- Apabila target yang akan di convert adalah werewolf maka target akan terbunuh
- Tidak dapat dibunuh vampire lainnya

**Minion (Evil/Vampires)**
Abilities:
- Mempunyai kemampuan membunuh dan menjadi pemimpin para Vampir
- Jika Dracula mati, maka ia akan menjadi Dracula dan kehilangan kekuatan membunuh
- Mengetahui Dracula

**Alpha Wolf (Evil/Werewolves)**
Abilities:
- Merubah 1 orang menjadi Werewolf tiap malam, target tidak akan mengetahui siapa yang meng-convert mereka (Kecuali Beta Wolf).
- Apabila target yang akan di convert adalah Vampire maka target akan terbunuh
- Tidak dapat dibunuh Werewolf lainnya

**Beta Wolf (Evil/Werewolves)**
Abilities:
- Mempunyai kemampuan membunuh dan menjadi pemimpin para Werewolf
- Jika Alpha wolf mati, maka ia akan menjadi alpha wolf
- Mengetahui Alpha Wolf

**Villager (Good/Villagers)**
Abilities:
- Bersama para penduduk memilih 1 orang setiap siang hari.

**Hunter (Good/Villagers)**
Abilities:
- Dapat Membunuh 1 orang pada fase malam
- Amunisi sang hunter sangat terbatas (1 wood stake dan 1 silver bullet)
- Werewolf mati jika dibunuh oleh silver bullet dan Vampire mati jika dibunuh dengan wood stake, Villager akan terbunuh dengan senjata mana pun.

**Priest (Good/Villagers)**
Abilities:
- Menjaga 1 orang (selain dirinya sendiri) Tiap malam dari serangan (baik untuk di-convert ataupun di bunuh)

**Seer (Good/Villagers)**
Abilities:
- Memeriksa 1 orang tiap malam (Primary role, Faksi dan alignment)
- Mengetahui Disciple

**Gypsy (Good/Villagers)**
Abilities:
- Memeriksa 1 orang tiap malam (Alignment Good atau Evil)

**Mason (Good/Villagers)**
Abilities:
- Mengetahui Semua Mason lainnya
- Apabila ada mason yang di convert, maka mason lainnya akan menerima kabar perubahan bentuk/faksi mason tersebut di awal fase malam berikutnya.

**Silversmith (Good/Villagers)**
Abilities:
- Tidak dapat diubah menjadi werewolf

**Saint (Good/Villagers)**
Abilities:
- Tidak dapat diubah menjadi Vampire

**Postman (Good/Villagers)**
Abilities:
- Jika dibunuh werewolf, werewolf mendapat additional 1 kill, malam berikutnya

**Diabetic (Good/Villagers)**
Abilities:
- Jika dibunuh Vampire, Vampire mendapat additional 1 kill, malam berikutnya

**Apoteker (Good/Villagers)**
Abilities:
- Dapat menyembuhkan pemain dari infeksi werewolf/vampire dengan memberikan 1 obat pada 1 orang pemain sehingga menjadi villager kembali. (Tidak mempengaruhi ability)
- Obat terbatas 2, Apoteker, Dracula dan Alpha kebal terhadap obat
- Pemain yang meminum obat 2x mati keracunan

**Scizophrenic (Good/Villagers)**
Abilities:
- Berubah peran secara random tiap malam (peran ditentukan GM)

**Copycat (Good/Villagers)**
Abilities:
- Memilih 1 orang pemain dan menduplikasi seluruh peran orang tersebut (1x)

**Disciple (Good/Villagers)**
Abilities:
- Jika seer mati, maka ia akan menjadi seer
- Mengetahui seer

**Brute (Good/Villagers)**
Abilities:
- Jika di bunuh oleh werewolf atau vampire mampu bertahan hingga siang hari untuk memberikan vote sebelum mati

**Prince (Good/Villagers)**
Abilities:
- Jika ia terpilih untuk di pancung, maka role-nya akan terbuka (Jika role terbuka karena terpilih di pancung maka orang pertama yang memilih dia pada hari itu yang akan dipancung) (1x)

**Excecutioner (Good/Villagers)**
Abilities:
- Jika ia terpilih untuk di pancung maka role-nya akan terbuka (Jika role terbuka karena terpilih di pancung maka orang terakhir yang memilih dia pada hari itu yang akan dipancung) (1x)

**Illusionist (Good/Villagers)**
Abilities:
- Jika ia terpilih untuk di bunuh malam hari maka tempatnya akan diganti oleh Double-nya (1x) (Peran double/orang yang menggantikan tempat-nya dipilih pada siang hari ke-1. Jika "double"-nya mati sebelum sang illusionist mati, maka illusionist diperkenankan untuk mengganti double-nya dengan penduduk yang lain)

**Prostitute (Good/Villagers)**
Abilities:
- Memeriksa 1 orang tiap malam (Membuka primary role, tetapi otomatis mati jika menemukan role werewolf atau vampire)

**The Pure Blood (Good/Villagers)**
Abilities:
- Kebal terhadap perubahan vampire dan werewolf (Jika diserang Dracula atau Alpha maka penyerangnya mati sementara ia tetap hidup)

**The Cursed (Good/Villagers)**
Abilities:
- Jika Mati akan membuka 1 primary role dan Faksi si pembunuh

## Peran Tambahan

**Vampire (Evil/ Vampires)**
Abilities:
- Vampire adalah pemain yang berhasil di convert Dracula (tanpa mengetahui siapa Dracula)
- Membunuh 1 orang tiap malam
- Peran utama dan kemampuan (ability) pemain tidak berubah
- Mengetahui Minion

**Werewolf (Evil/Werewolves)**
Abilities:
- Werewolf adalah pemain yang berhasil di convert Alpha Wolf (tanpa mengetahui siapa Alpha Wolf)
- Membunuh 1 orang tiap malam
- Peran utama dan kemampuan (ability) pemain tidak berubah
- Mengetahui Beta Wolf

**The Guardian (Good/Villagers)**
Abilities:
- Dipilih dari Majority vote penduduk, jika jumlah vote untuk menjadi the Guardian sama, maka GM akan melempar koin untuk menentukan siapa yang akan menjadi the Guardian.
- Kebal dari segala bentuk serangan di malam hari
- Memilih 1 orang penduduk untuk dijaga dari serangan apapun pada malam hari
- The Guardian dan orang yang dipilih oleh the Guardian kehilangan seluruh Night Ability

## Holy Items

Silver Stake : Senjata ini digunakan untuk meng-eksekusi pemain yang terpilih untuk dieksekusi hari itu. Setelah siang hari berakhir, senjata ini diberikan pada Guardian. Item ini adalah senjata "penjaga" dari evil creature baik terhadap dirinya ataupun orang yang di lindungi.

Item lain dan cara mendapatkan-nya bisa dilihat pada post Om PJ di bawah

## Finding Item
Peta Desa CYSTG

[Board Games - TWG III] Werewolves VS Vampires :::Twilight:::

List Item Yang Bisa Dicari:
No. Item (User/Target/Fase/Sifat/Batas Pemakaian)

**Holy Silver Cross (good/evil/malam/pasif/3x)**
- Melindungi dari tindakan evil creature.
- Tak ada efek jika dimiliki oleh evil creature.

**Holy Water (all/evil/siang & malam/pasif & aktif/1x)**
- Jika diserang oleh evil creature, maka si penyerang berubah menjadi good (tak berlaku ke Alpha dan Dracula).
- Jika diinfeksi Alpha/ Dracula, Holy Water bisa menetralisir transformasi. Bisa diminumkan ke pemain evil, ia akan menjadi good.

**Revolver (all/vamp & were/malam/pasif/1x)**
- Hanya ada satu peluru, jika ditembakkan saat diserang akan membuat penyerangnya mati (vampire/were).
- Tak kebal jika diinfeksi Dracula/Alpha.
- Jika guard menjaga, maka revolver tak digunakan.

**Stun Gun (all/evil/malam/pasif/1x)**
- Membuat evil creature gagal membunuh/infeksi.

**Garlic Necklace (all/vampire/malam/pasif/1x)**
- Menghindar dari serangan vampire dan Dracula.

**Wolfsbane potion (all/werewolf/malam/pasif/1x)**
- Menghindar dari serangan were dan Alpha.

**Bulletproof Vest (all/hunter&revolver/malam/pasif/1x)**
- Membuat serangan Hunter atau tembakan revolver gagal.

**Invisible Cloak (all/self/malam/aktif/1x)**
- Menghilang saat malam sehingga tak bisa menjadi target siapapun.

**Handcuffs (all/all/siang/aktif/1x)**
- Membuat vote 1 pemain tak dihitung pada fase siang.

**Soul Binder Scroll (evil/all/siang & malam/aktif/1x)**
- Mantra dengan kekuatan jahat yang mampu mengunci seluruh kekuatan (Primary Role) 1 orang pemain selama 2 fase.
- Hanya dapat digunakan oleh alignment evil

**Surveillance Camera (all/all/malam/aktif/unlimited)**
- Mengetahui apakah malam tersebut orang yang dipilih bangun (mempunyai night role dan memakai hak-nya) atau Tidur (tidak punya night role atau punya night role tapi tidak mempergunakan haknya).

**Exorcism Spell (all/hantu/siang & malam/aktif/1x)**
- Membangkitkan arwah hantu menjadi hidup dengan role random.
- Tidak berguna bagi pemegang item, namun bisa membantu hantu kembali bermain.

**Life Tablet (all/self/siang & malam/otomatis/)**
- Jika diminum semasa hidup akan membuat ia hidup sekali lagi jika mati (tidak berlaku bagi Dracula dan Alpha).
- Hidup kembali di fase berikutnya dengan role baru (random). Hantu tak bisa minum ini.

**Empty Body (hantu/self/siang & malam/otomatis/)**
- Hantu yg menemukan akan hidup kembali di fase berikutnya (role baru random).
- Pemain hidup yang menemukan tak bisa mengambil item ini tapi boleh membisikkan ke para hantu.

**Seer Cloth (all/seer/siang & malam/otomatis/)**
- Mampu mengenali Seer

**Mason ID Card (all/mason/siang & malam/otomatis/)**
- Mampu mengenali salah satu Mason (hidup/mati, random)

**Prince Shoes (all/prince/siang & malam/otomatis/)**
- Mampu mengidentifikasi Prince.

# Additional Rules

+ Game Finding Item dimulai pada Fase Siang Pertama
+ Jika ingin mengambil sebuah item harus melalui PM ke Co-GM (pasirjengkol). Jika inbox Co-GM penuh, silahkan PM ke GM (lukystar) sebagai barang bukti pengambilan. Item bisa digunakan setelah ada konfirmasi dari GM/Co-GM.
+ Dalam 1 fase hanya boleh mengambil 1 item.
+ Setelah item diambil, akan ada pemberitahuan di trit bahwa brankas telah dibuka.
+ Item tidak dapat dipindahtangankan ke pemain lain.
+ Jika seorang pemain mati, ia akan kehilangan semua itemnya. Item tersebut otomatis hangus. Dan jika ia hidup kembali, item-item tersebut tak lagi ia miliki.
+ Jika seorang pemain memiliki lebih dari 1 item pasif, maka item dengan nomor urut terendah yang akan digunakan pertama kali.
+ Item aktif digunakan dengan cara PM ke GM (lukystar) pada fase yang sesuai.
+ GM dan Co-GM tidak melayani permintaan clue melalui PM. PM yang meminta clue akan otomatis diabaikan. Semua pertanyaan ataupun minta petunjuk bisa dilakukan melalui post di trit ini.
+ Keistimewaan diberikan kepada Hunter untuk memberikan 1 pertanyaan ke Co-GM pada setiap fase (kecuali jika menggunakan Night Role).
+ Non Pemain TWG dilarang memberikan clue/jawaban di dalam trit ini



Seluruh Brankas Telah terbuka.

GAME OVER

VILLAGERS WIN

# Behind The Scene
